### PR TITLE
add load balancer health check

### PR DESCRIPTION
**Pull request by qiutingjun**
- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

### What type of this PR
Examples of user facing changes:
- Features
- 
add  health check for load balancer

### Which issue(s) this PR fixes:
Fixes #(issue-number)

### <samp>🤖 Generated by Copilot at 6edffc4</samp>

This pull request adds support for IP port mappings and health checks for load balancers in vpc subnets. It modifies the `LoadBalancer` and `OvnClient` interfaces and their mock and implementation methods in the `pkg/ovs` and `pkg/controller` packages. It also adds and improves unit tests and error handling code, and fixes some typos and whitespace issues.

### <samp>🤖 Generated by Copilot at 6edffc4</samp>

> _We're the crew of the `OvnClient` ship, we sail the vpc seas_
> _We make the load balancers work with health checks and IPs_
> _We pull the code and fix the bugs, we write the tests and docs_
> _We heave ho, we heave ho, we heave ho on the count of three_

### <samp>🤖 Generated by Copilot at 6edffc4</samp>

*  Add and implement load balancer health check and IP port mapping methods to the `LoadBalancer` and `OvnClient` interfaces ([link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-50fe35ba11ad04edb53bfaccef915df3650a81844495ed73d3c158e975c04c49L88-R103), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-50fe35ba11ad04edb53bfaccef915df3650a81844495ed73d3c158e975c04c49R183), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-bfd041dba2e9723d827d8cb8319204ff483edd6d1489966769e2718c61202453R1-R313))
*  Add and update mock methods for load balancer health check and IP port mapping to the `MockLoadBalancer` and `MockOvnClient` interfaces ([link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-2eadf7fb3dd75cdfd04457a9b7e244a2bfb9aa9bb790ff6ed89b86599c0a4c71L951-R982), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-2eadf7fb3dd75cdfd04457a9b7e244a2bfb9aa9bb790ff6ed89b86599c0a4c71L964-R1025), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-2eadf7fb3dd75cdfd04457a9b7e244a2bfb9aa9bb790ff6ed89b86599c0a4c71R1055-R1068), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-2eadf7fb3dd75cdfd04457a9b7e244a2bfb9aa9bb790ff6ed89b86599c0a4c71R1083-R1192), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-2eadf7fb3dd75cdfd04457a9b7e244a2bfb9aa9bb790ff6ed89b86599c0a4c71R2330-R2343), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-2eadf7fb3dd75cdfd04457a9b7e244a2bfb9aa9bb790ff6ed89b86599c0a4c71R2625-R2652), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-2eadf7fb3dd75cdfd04457a9b7e244a2bfb9aa9bb790ff6ed89b86599c0a4c71R2920-R2934), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-2eadf7fb3dd75cdfd04457a9b7e244a2bfb9aa9bb790ff6ed89b86599c0a4c71R3085-R3099), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-2eadf7fb3dd75cdfd04457a9b7e244a2bfb9aa9bb790ff6ed89b86599c0a4c71L3028-R3311), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-2eadf7fb3dd75cdfd04457a9b7e244a2bfb9aa9bb790ff6ed89b86599c0a4c71L3041-R3354), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-2eadf7fb3dd75cdfd04457a9b7e244a2bfb9aa9bb790ff6ed89b86599c0a4c71R3384-R3412))
*  Add and modify test functions for load balancer health check and IP port mapping methods in the `pkg/ovs/ovn-nb-suite_test.go` file ([link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-5d9e40841703fc05abd0bdae3efc305752b84e9c573472da709ed8326a855453R333-R336), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-5d9e40841703fc05abd0bdae3efc305752b84e9c573472da709ed8326a855453L345-L348), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-5d9e40841703fc05abd0bdae3efc305752b84e9c573472da709ed8326a855453R357-R405), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-5d9e40841703fc05abd0bdae3efc305752b84e9c573472da709ed8326a855453R794))
*  Add `mappings` parameter to the `LoadBalancerAddVip` method of the `LoadBalancer` interface and pass it to the base method ([link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-50fe35ba11ad04edb53bfaccef915df3650a81844495ed73d3c158e975c04c49L81-R81), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-2eadf7fb3dd75cdfd04457a9b7e244a2bfb9aa9bb790ff6ed89b86599c0a4c71L3028-R3311))
*  Add `mappings` argument to the `LoadBalancerAddVip` method calls in the `handleUpdateEndpoint` and `handleDelOvnDnatFinalizer` functions in the `pkg/controller/endpoint.go` and `pkg/controller/ovn_dnat.go` files, respectively ([link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-e446ff04750bbbe87ec6cf1387960a29d56757d84784b18f2814a6e0be5fb528L193-R204), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-7fa512aca42bc3bdafdaed430f6c2000a24cdf0973b09a703a88c7a9b7b054d1L590-R623))
*  Add `gateways` parameter to the `getMappedServicePortBackends` function in the `pkg/controller/endpoint.go` file and use it to generate named IPs for the load balancer ([link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-e446ff04750bbbe87ec6cf1387960a29d56757d84784b18f2814a6e0be5fb528L265-R324))
*  Add `getVpcSubnetGateways` function to the `pkg/controller/endpoint.go` file and call it in the `handleUpdateEndpoint` function to get the gateways of the subnets in the vpc ([link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-e446ff04750bbbe87ec6cf1387960a29d56757d84784b18f2814a6e0be5fb528L220-R264), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-e446ff04750bbbe87ec6cf1387960a29d56757d84784b18f2814a6e0be5fb528R175-R179))
*  Add `TargetRef` to the `EndpointAddress` objects in the `generateEndpoints` function in the `pkg/controller/switch_lb_rule.go` file and use it to generate named IPs for the load balancer ([link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-1bbd8fc68082905bd8c8204a29a746985193081fb932bedaa86f4f25abc2dc02L336-R348))
*  Add `err` variable declaration blocks to the `InitOVN` and `initLB` functions in the `pkg/controller/init.go` file and change the `:=` operator to the `=` operator for the `err` variable assignments ([link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-92aa62435bc2b1b2be34f478f650597068bcf35b8d5975d119f91cf78ac54988L25-R29), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-92aa62435bc2b1b2be34f478f650597068bcf35b8d5975d119f91cf78ac54988L31-R35), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-92aa62435bc2b1b2be34f478f650597068bcf35b8d5975d119f91cf78ac54988L37-R41), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-92aa62435bc2b1b2be34f478f650597068bcf35b8d5975d119f91cf78ac54988L44-R58), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-92aa62435bc2b1b2be34f478f650597068bcf35b8d5975d119f91cf78ac54988L208-R221), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-92aa62435bc2b1b2be34f478f650597068bcf35b8d5975d119f91cf78ac54988L219-R227))
*  Fix typo in the log message of the `gcLoadBalancer` function in the `pkg/controller/gc.go` file ([link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-efdb6355f2187b31e5e61610c24bf4d446a23d814d51448c170a91ef96ae1e89L393-R393))
*  Add `strings` import to the `pkg/controller/endpoint.go` file ([link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-e446ff04750bbbe87ec6cf1387960a29d56757d84784b18f2814a6e0be5fb528R6))
*  Remove unnecessary whitespace in the `pkg/ovs/ovn-nb-logical_router.go` and `pkg/ovs/ovn-nb-suite_test.go` files ([link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-b193db1a9429f799227f035b255c48693043e1807435a181bae5f5f58c05aadaR1-R213), [link](https://github.com/kubeovn/kube-ovn/pull/3070/files?diff=unified&w=0#diff-963d5ab25c32b9009a860d464ff78138edef57c9d41f2fc4209510980ec7b51eL177))

### CODE REVIEW

**Comment by qiutingjun** [comment]
配置health check 继续测试

[[参考ovn-nb文档](https://www.ovn.org/support/dist-docs/ovn-nb.5.html)](https://www.ovn.org/support/dist-docs/ovn-nb.5.html)

``` bash
     Health Checks:

       OVN  supports  health checks for load balancer endpoints, for IPv4 load
       balancers only. When health checks are enabled, the load balancer  uses
       only healthy endpoints.

       Suppose      that      vips      contains      a     key-value     pair
       10.0.0.10:80=10.0.0.4:8080,20.0.0.4:8080. 
       To enable health  checks  for this  virtual’s endpoints, 
       add two key-value pairs to ip_port_mappings,
       with keys 10.0.0.4 and 20.0.0.4, 
       and add to health_check a reference to
       a Load_Balancer_Health_Check row whose vip is set to 10.0.0.10.

       health_check: set of Load_Balancer_Health_Checks
              Load balancer health checks associated with this load balancer.

       ip_port_mappings: map of string-string pairs
              Maps  from endpoint IP to a colon-separated pair of logical port
              name and source IP, e.g. port_name:sourc_ip. Health  checks  are
              sent to this port with the specified source IP.

              For  example, in the example above, IP to port mappings might be
              defined         as         10.0.0.4=sw0-p1:10.0.0.2          and
              20.0.0.4=sw1-p1:20.0.0.2,  if  the  values  given  were suitable
              ports and IP addresses.


```



```bash
uuid=`ovn-nbctl --bare --columns _uuid find load_balancer name=test-vpc3-tcp-lb0`

# 关联 ip_port_mappings 到loadbalancer

ovn-nbctl --wait=sb set load_balancer $uuid ip_port_mappings:192.168.4.4=vpc3-busybox03.vpc3:192.168.4.14

ovn-nbctl --wait=sb set load_balancer $uuid ip_port_mappings:192.168.4.5=vpc3-busybox04.vpc3:192.168.4.15

uuid3=`ovn-nbctl --id=@hc create Load_Balancer_Health_Check vip="10.120.31.215\:8000" -- add Load_Balancer $uuid health_check @hc`

# echo $uuid3
66117312-2b7a-4920-b903-fadb3a842b3b

ovn-nbctl set Load_Balancer_Health_Check $uuid3 options:interval=5 options:timeout=20 options:success_count=3 options:failure_count=3



# ovn-nbctl list Load_Balancer_Health_Check
_uuid               : 66117312-2b7a-4920-b903-fadb3a842b3b
external_ids        : {}
options             : {failure_count="3", interval="5", success_count="3", timeout="20"}
vip                 : "10.120.31.215:8000"

```

**Comment by oilbeater** [comment]
The ut should be fixed @qiutingjun

**Comment by bobz965** [comment]
我基于该PR的测试方式和测试结果

```
# 1. 基于当前的 master 分支测试通过

(.venv) root@empty:~/test/kube-ovn/health-check-1.12# cat 01.ns-vpc-subnet.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns1
---
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: vpc1
spec:
  namespaces:
  - ns1
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: vpc1-subnet1
spec:
  cidrBlock: 10.1.0.0/24
  default: false
  disableGatewayCheck: false
  disableInterConnection: true
  enableEcmp: false
  gatewayNode: ""
  gatewayType: distributed
  natOutgoing: false
  private: false
  protocol: IPv4
  provider: ovn
  vpc: vpc1
  namespaces:
  - ns1


(.venv) root@empty:~/test/kube-ovn/health-check-1.12# cat 02.pod.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: lb-client
  namespace: ns1
  annotations:
    ovn.kubernetes.io/logical_switch: vpc1-subnet1
    ovn.kubernetes.io/ip_pool: 10.1.0.4
spec:
  containers:
    - name: lb-client
      image: docker.io/nicolaka/netshoot:latest
      imagePullPolicy: Never
      command:
        - sh
        - -c
        - "sleep infinity"
      securityContext:
        capabilities:
          add:
            - NET_ADMIN


---
apiVersion: v1
kind: Pod
metadata:
  name: netshoot-1
  namespace: ns1
  annotations:
    ovn.kubernetes.io/logical_switch: vpc1-subnet1
    ovn.kubernetes.io/ip_pool: 10.1.0.5
  labels:
    app: netshoot
spec:
  containers:
    - name: netshoot
      image: docker.io/nicolaka/netshoot:latest
      imagePullPolicy: Never
      command:
        - sh
        - -c
        - echo `hostname` > index.html; python -m http.server
      securityContext:
        capabilities:
          add:
            - NET_ADMIN


---
apiVersion: v1
kind: Pod
metadata:
  name: netshoot-2
  namespace: ns1
  annotations:
    ovn.kubernetes.io/logical_switch: vpc1-subnet1
    ovn.kubernetes.io/ip_pool: 10.1.0.6
  labels:
    app: netshoot
spec:
  containers:
    - name: netshoot
      image: docker.io/nicolaka/netshoot:latest
      imagePullPolicy: Never
      command:
        - sh
        - -c
        - echo `hostname` > index.html; python -m http.server
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
(.venv) root@empty:~/test/kube-ovn/health-check-1.12# cat 03.
03.external-vip-slr.yaml  03.slr.yaml
(.venv) root@empty:~/test/kube-ovn/health-check-1.12# cat 03.slr.yaml
---

apiVersion: kubeovn.io/v1
kind: Vip
metadata:
  name: arp-proxy-vip1
spec:
  namespace: ns1
  subnet: vpc1-subnet1
  v4ip: 10.1.0.100
  type: switch_lb_vip


---
apiVersion: kubeovn.io/v1
kind: SwitchLBRule
metadata:
  name: netshoot
spec:
  vip: 10.1.0.100
  sessionAffinity: ClientIP
  namespace: ns1
  selector:
    - app:netshoot
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP

# 单独执行 lb health check 的执配置脚本

(.venv) root@empty:~/test/kube-ovn/health-check-1.12# cat 04.add-subnet-vip-hc-to-lb.sh
# cat config_health_check.sh
# lb 是基于 slr 触发维护的，已经绑定到 subnet，只需要配置 健康检查 即可

kubectl ko nbctl ls-lb-list vpc1-subnet1
lb=vpc-vpc1-tcp-sess-load
lb_uuid=`kubectl ko nbctl --bare --columns _uuid find Load_Balancer name=$lb`
echo "uuid $lb_uuid"

vip="10.1.0.100"
hcvip="10.1.0.100"

kubectl ko nbctl --wait=sb set load_balancer $lb_uuid ip_port_mappings:10.1.0.5=netshoot-1.ns1:$hcvip
# 使用同一个 同网段 vip
kubectl ko nbctl --wait=sb set load_balancer $lb_uuid ip_port_mappings:10.1.0.6=netshoot-2.ns1:$hcvip

health_check_id=`kubectl ko nbctl --id=@hc create Load_Balancer_Health_Check vip="10.1.0.100\:80" -- add Load_Balancer $lb_uuid health_check @hc`
echo "health_check_id $health_check_id"
kubectl ko nbctl set Load_Balancer_Health_Check $health_check_id options:interval=5 options:timeout=20 options:success_count=3 options:failure_count=3



```


该 pr 的实现仅仅是将上述步骤的第四个脚本`健康检查部分`编排一下，只需要执行前三项，支持基于slr 的 lb 自动添加健康检查即可。 目前认为在编码上已实现和手动执行第二个脚本一样的结果。而且 结果一致。


image



虽然结果一致，但是基于 LB 前端 IP 访问，网络不通

**Comment by bobz965** [comment]
# 手动配置健康检查的一些流程

``` bash

(.venv) root@empty:~/test/kube-ovn/health-check-1.12# k exec -it -n ns1           lb-client -- bash
lb-client:~# curl 10.1.0.100
netshoot-1
lb-client:~# curl 10.1.0.100
netshoot-1
lb-client:~# curl 10.1.0.100
netshoot-1
lb-client:~#
exit
(.venv) root@empty:~/test/kube-ovn/health-check-1.12# ./show
kubectl ko nbctl find Load_Balancer name=vpc-vpc1-tcp-sess-load

_uuid               : 1c481d4e-00fa-4c5c-bf50-5e9460e6a687
external_ids        : {}
health_check        : []
ip_port_mappings    : {}
name                : vpc-vpc1-tcp-sess-load
options             : {affinity_timeout="10800"}
protocol            : tcp
selection_fields    : [ip_src]
vips                : {"10.1.0.100:80"="10.1.0.5:8000,10.1.0.6:8000"}

kubectl ko nbctl list Load_Balancer_Health_Check


kubectl ko sbctl list Service_Monitor


(.venv) root@empty:~/test/kube-ovn/health-check-1.12# ./04.add-subnet-vip-hc-to-lb.sh
UUID                                    LB                  PROTO      VIP              IPs
1c481d4e-00fa-4c5c-bf50-5e9460e6a687    vpc-vpc1-tcp-ses    tcp        10.1.0.100:80    10.1.0.5:8000,10.1.0.6:8000
uuid 1c481d4e-00fa-4c5c-bf50-5e9460e6a687
health_check_id bd656c23-2555-4362-a644-01d4f778396c
(.venv) root@empty:~/test/kube-ovn/health-check-1.12# ./show
kubectl ko nbctl find Load_Balancer name=vpc-vpc1-tcp-sess-load

_uuid               : 1c481d4e-00fa-4c5c-bf50-5e9460e6a687
external_ids        : {}
health_check        : [bd656c23-2555-4362-a644-01d4f778396c]
ip_port_mappings    : {"10.1.0.5"="netshoot-1.ns1:10.1.0.100", "10.1.0.6"="netshoot-2.ns1:10.1.0.100"}
name                : vpc-vpc1-tcp-sess-load
options             : {affinity_timeout="10800"}
protocol            : tcp
selection_fields    : [ip_src]
vips                : {"10.1.0.100:80"="10.1.0.5:8000,10.1.0.6:8000"}

kubectl ko nbctl list Load_Balancer_Health_Check

_uuid               : bd656c23-2555-4362-a644-01d4f778396c
external_ids        : {}
options             : {failure_count="3", interval="5", success_count="3", timeout="20"}
vip                 : "10.1.0.100:80"

kubectl ko sbctl list Service_Monitor

_uuid               : 15ef7cd6-47bd-4015-a777-9847c4c2c073
external_ids        : {}
ip                  : "10.1.0.5"
logical_port        : netshoot-1.ns1
options             : {failure_count="3", interval="5", success_count="3", timeout="20"}
port                : 8000
protocol            : tcp
src_ip              : "10.1.0.100"
src_mac             : "42:e5:76:11:4f:f6"
status              : online

_uuid               : e0b1573b-8bd1-4df0-9499-324e82363ebc
external_ids        : {}
ip                  : "10.1.0.6"
logical_port        : netshoot-2.ns1
options             : {failure_count="3", interval="5", success_count="3", timeout="20"}
port                : 8000
protocol            : tcp
src_ip              : "10.1.0.100"
src_mac             : "42:e5:76:11:4f:f6"
status              : online

(.venv) root@empty:~/test/kube-ovn/health-check-1.12#
(.venv) root@empty:~/test/kube-ovn/health-check-1.12#
(.venv) root@empty:~/test/kube-ovn/health-check-1.12# k exec -it -n ns1           lb-client -- bash
lb-client:~# curl 10.1.0.100
netshoot-1
lb-client:~# curl 10.1.0.100
netshoot-1
lb-client:~# curl 10.1.0.100
netshoot-1
lb-client:~#
exit
(.venv) root@empty:~/test/kube-ovn/health-check-1.12# k delete po -n ns1           netshoot-1
pod "netshoot-1" deleted
(.venv) root@empty:~/test/kube-ovn/health-check-1.12# k exec -it -n ns1           lb-client -- bash
lb-client:~# curl 10.1.0.100
netshoot-2
lb-client:~# curl 10.1.0.100
netshoot-2
lb-client:~# curl 10.1.0.100
netshoot-2
lb-client:~#
exit
(.venv) root@empty:~/test/kube-ovn/health-check-1.12# ./show
kubectl ko nbctl find Load_Balancer name=vpc-vpc1-tcp-sess-load

_uuid               : 1c481d4e-00fa-4c5c-bf50-5e9460e6a687
external_ids        : {}
health_check        : [bd656c23-2555-4362-a644-01d4f778396c]
ip_port_mappings    : {"10.1.0.5"="netshoot-1.ns1:10.1.0.100", "10.1.0.6"="netshoot-2.ns1:10.1.0.100"}
name                : vpc-vpc1-tcp-sess-load
options             : {affinity_timeout="10800"}
protocol            : tcp
selection_fields    : [ip_src]
vips                : {"10.1.0.100:80"="10.1.0.6:8000"}

kubectl ko nbctl list Load_Balancer_Health_Check

_uuid               : bd656c23-2555-4362-a644-01d4f778396c
external_ids        : {}
options             : {failure_count="3", interval="5", success_count="3", timeout="20"}
vip                 : "10.1.0.100:80"

kubectl ko sbctl list Service_Monitor

_uuid               : e0b1573b-8bd1-4df0-9499-324e82363ebc
external_ids        : {}
ip                  : "10.1.0.6"
logical_port        : netshoot-2.ns1
options             : {failure_count="3", interval="5", success_count="3", timeout="20"}
port                : 8000
protocol            : tcp
src_ip              : "10.1.0.100"
src_mac             : "42:e5:76:11:4f:f6"
status              : online

(.venv) root@empty:~/test/kube-ovn/health-check-1.12#





################ 3.  配置 lbhc 之后

###### 抓包


root@kube-ovn-worker:/kube-ovn# tcpdump -i any host 10.1.0.100 -netvv
tcpdump: data link type LINUX_SLL2
tcpdump: listening on any, link-type LINUX_SLL2 (Linux cooked v2), snapshot length 262144 bytes
b8c29b1035b3_h Out ifindex 19 42:e5:76:11:4f:f6 ethertype IPv4 (0x0800), length 60: (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    10.1.0.100.61621 > 10.1.0.6.8000: Flags [S], cksum 0x8976 (correct), seq 3797164333, win 65160, length 0
b8c29b1035b3_h P   ifindex 19 00:00:00:de:14:77 ethertype IPv4 (0x0800), length 64: (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 44)
    10.1.0.6.8000 > 10.1.0.100.61621: Flags [S.], cksum 0x148a (incorrect -> 0x0b2e), seq 486885730, ack 3797164334, win 65280, options [mss 1360], length 0
b8c29b1035b3_h Out ifindex 19 42:e5:76:11:4f:f6 ethertype IPv4 (0x0800), length 60: (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    10.1.0.100.61621 > 10.1.0.6.8000: Flags [R.], cksum 0x22fa (correct), seq 2, ack 1, win 65160, length 0







b8c29b1035b3_h Out ifindex 19 42:e5:76:11:4f:f6 ethertype IPv4 (0x0800), length 60: (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    10.1.0.100.22177 > 10.1.0.6.8000: Flags [S], cksum 0x8251 (correct), seq 2625505341, win 65160, length 0
b8c29b1035b3_h P   ifindex 19 00:00:00:de:14:77 ethertype IPv4 (0x0800), length 64: (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 44)
    10.1.0.6.8000 > 10.1.0.100.22177: Flags [S.], cksum 0x148a (incorrect -> 0x5062), seq 566098000, ack 2625505342, win 65280, options [mss 1360], length 0
b8c29b1035b3_h Out ifindex 19 42:e5:76:11:4f:f6 ethertype IPv4 (0x0800), length 60: (tos 0x0, ttl 63, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    10.1.0.100.22177 > 10.1.0.6.8000: Flags [R.], cksum 0x682e (correct), seq 2, ack 1, win 65160, length 0




(.venv) root@empty:~/test/kube-ovn/health-check-1.12#

```

**Comment by bobz965** [comment]
实际测试过程中，发现，健康检查的创建和更新到lb中需要在一个事务中，在命令行操作中多了一个 操作`op`,那就是等待，
目前的编码过程中， 没有等待的 OP



``` bash

[
    "OVN_Northbound",
    {
        "where":[
            [
                "_uuid",
                "==",
                [
                    "uuid",
                    "6d20899b-319d-40c6-bef2-a82f17c42ae5"
                ]
            ]
        ],
        "table":"Load_Balancer",
        "timeout":0,
        "op":"wait",  # 等待
        "rows":[
            {
                "health_check":[
                    "set",
                    [

                    ]
                ]
            }
        ],
        "columns":[
            "health_check"
        ],
        "until":"=="
    },
    {
        "row":{
            "vip":"10.96.0.1:53" # lbhc 表 插入一行
        },
        "table":"Load_Balancer_Health_Check",
        "op":"insert",          # 插入
        "uuid-name":"row321b93c4_d6a6_44b5_91f8_e2f612beeeda"
    },
    {
        "row":{
            "health_check":[
                "named-uuid",
                "row321b93c4_d6a6_44b5_91f8_e2f612beeeda"
            ]
        },
        "where":[
            [
                "_uuid",
                "==",
                [
                    "uuid",
                    "6d20899b-319d-40c6-bef2-a82f17c42ae5"
                ]
            ]
        ],
        "table":"Load_Balancer",
        "op":"update" # 更新
    },
    {
        "op":"comment",
        "comment":"ovn-nbctl: ovn-nbctl -v --id=@hc create Load_Balancer_Health_Check \"vip=10.96.0.1\\\\:53\" -- add Load_Balancer 6d20899b-319d-40c6-bef2-a82f17c42ae5 health_check @hc"
    }
]

```

**Pull request closed without merging**
