### PR TITLE
feat: support VLAN subnet in VPC

### PR DESCRIPTION
**Pull request by fanriming**
#### What type of this PR
Examples of user facing changes:
- API changes

1. In a custom VPC, both overlay and underlay subnets can be routed.
2. Set 'ovn-chassis-mac-mappings' for provider to avoid mac moves on Top of the Rack (TOR) switch. Reference link : https://www.openvswitch.org/support/ovscon2018/6/1440-sharma.pdf

### CODE REVIEW

**Comment by zhangzujian** [comment]
Nice work!

Only one suggestion - We can add a field in subnet spec to control the feature, so that users can use "pure" underlay network in custom VPCs and we can provide compability.

**Comment by fanriming** [comment]
> Nice work!
> 
> Only one suggestion - We can add a field in subnet spec to control the feature, so that users can use "pure" underlay network in custom VPCs and we can provide compability.

@zhangzujian Thank you for your suggestion.
In my opinion, a pure underlay network is irrelevant to a VPC because there is no logical router for it. If we want to use a "pure" underly network, simply leave the "VPC" field blank.

**Comment by zhangzujian** [comment]
How does the `ovn-chassis-mac-mappings` configuration take effect? I tried to figure it out by capturing packets between Pods and between Pod and OVN router, but no significant changes were observed.

**Comment by fanriming** [comment]
> How does the `ovn-chassis-mac-mappings` configuration take effect? I tried to figure it out by capturing packets between Pods and between Pod and OVN router, but no significant changes were observed.

Pod does not sense this change, but the physical switch does.
If 'ovn-chassis-mac-mappings' is not configured, the MAC address table on the physical switch frequently changes:
image

Continuous mac move of logical router port macs.
- Logical router ports are distributed across hypervisors.
- Packets with logical router port MAC address as source MAC will come from multiple chassis.
- Will cause mac moves on Top of the Rack (TOR) switch.
   ■ As a security measure packets could be dropped.
   ■ As a security measure corresponding TOR switch port could be blocked.

https://www.openvswitch.org/support/ovscon2018/6/1440-sharma.pdf

**Review by zhangzujian — APPROVED** [review]
LGTM, Thanks!

**Pull request merged**
