### PR TITLE
u2o feature

### LINKED ISSUE #2050: Interconnection between overlay and underlay subnet.
### Feature request

When underlay and overlay subnet coexist, workload in underlay subnet cannot visit services in overlay subnet. In kubevirt case, most users will run vm instances in underlay subnet to connect directly into external physical network. But also need to visit some services in kubernetes that run as containers and live in overlay subnet.

### Howto

Kube-OVN already has logical gateway function which can connect underlay subnet into the overlay network, we need to extend it to make logical gateway and physical gateway coexist in a subnet and add related route to redirect traffic.

### PR DESCRIPTION
**Pull request by changluyi**
- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

#### What type of this PR
Examples of user facing changes:
- Features
underlay and overlay subnet interconnect
- Bug fixes
- Docs
- Tests

```
policy1:
prio 31000 match: "ip4.dst == underlay subnet cidr && ip4.dst != node ips"  action: allow

policy2:
prio 31000 match: "ip4.dst == node ips && ip4.src == underlay subnet cidr"  action: allow

policy3:
prio 29000 match: "ip4.src == underlay subnet cidr"                         action: reroute physical gw

comment:
policy1 and policy2 allow overlay pod access underlay but when overlay pod access node ip, it should go join subnet,
policy3: underlay pod first access u2o interconnection lrp and then reoute to physical gw
```

#### Which issue(s) this PR fixes:
Fixes #2050

### CODE REVIEW

**Comment by oilbeater** [comment]
重启 kube-ovn-controller 后发现如下问题：
1. Pod 会使用到 u2oInterconnectionIP

```yaml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  creationTimestamp: "2022-12-26T07:07:03Z"
  finalizers:
  - kube-ovn-controller
  generation: 2
  name: ovn-default
  resourceVersion: "2289"
  uid: de28ba31-a48e-4302-a20e-b81892d8533b
spec:
  cidrBlock: 172.18.0.0/16,fc00:f853:ccd:e793::/64
  default: true
  excludeIps:
  - 172.18.0.1
  - 172.18.0.2
  - 172.18.0.3
  - fc00:f853:ccd:e793::1
  - fc00:f853:ccd:e793::2
  - fc00:f853:ccd:e793::3
  gateway: 172.18.0.1,fc00:f853:ccd:e793::1
  gatewayNode: ""
  gatewayType: distributed
  natOutgoing: true
  private: false
  protocol: Dual
  provider: ovn
  u2oInterconnection: true
  vlan: ovn-vlan
  vpc: ovn-cluster
status:
  activateGateway: ""
  conditions:
  - lastTransitionTime: "2022-12-26T07:07:06Z"
    lastUpdateTime: "2022-12-26T07:11:29Z"
    reason: ResetLogicalSwitchAclSuccess
    status: "True"
    type: Validated
  - lastTransitionTime: "2022-12-26T07:07:06Z"
    lastUpdateTime: "2022-12-26T07:07:06Z"
    reason: ResetLogicalSwitchAclSuccess
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-12-26T07:07:06Z"
    lastUpdateTime: "2022-12-26T07:07:06Z"
    message: Not Observed
    reason: Init
    status: Unknown
    type: Error
  dhcpV4OptionsUUID: ""
  dhcpV6OptionsUUID: ""
  u2oInterconnectionIP: 172.18.0.4,fc00:f853:ccd:e793::4
  v4availableIPs: 65526
  v4usingIPs: 5
  v6availableIPs: 1.8446744073709552e+19
  v6usingIPs: 5
```

```
I1226 07:13:20.391305      13 ipam.go:51] allocate v4 172.18.0.4 v6 fc00:f853:ccd:e793::4 mac 00:00:00:0D:DE:93 for kube-system/kube-ovn-pinger-bqw2c from subnet ovn-default
```

2. 日志中存在反复 add/remove 路由的日志

```
I1226 07:11:29.229293      13 subnet.go:2119] add u2o interconnection policy for router: ovn-cluster, match ip4.dst == 172.18.0.0/16 && ip4.dst != $ovn.default.u2o_exclude_ip.ip4, action allow
I1226 07:11:29.240596      13 ovn-nbctl-legacy.go:1017] remove inconsistent policy route from router ovn-cluster: match ip4.dst == 172.18.0.0/16 && ip4.dst != $ovn.default.u2o_exclude_ip.ip4
I1226 07:11:29.246036      13 ovn-nbctl-legacy.go:1073] remove policy route from router ovn-cluster: match ip4.dst == 172.18.0.0/16 && ip4.dst != $ovn.default.u2o_exclude_ip.ip4
I1226 07:11:29.255270      13 ovn-nbctl-legacy.go:1028] add policy route for router ovn-cluster: priority 31000, match ip4.dst == 172.18.0.0/16 && ip4.dst != $ovn.default.u2o_exclude_ip.ip4, nextHop
I1226 07:11:29.293086      13 subnet.go:2125] add u2o interconnection policy for router: ovn-cluster, match ip4.dst == $ovn.default.u2o_exclude_ip.ip4 && ip4.src == 172.18.0.0/16, action allow
I1226 07:11:29.312550      13 ovn-nbctl-legacy.go:1017] remove inconsistent policy route from router ovn-cluster: match ip4.dst == $ovn.default.u2o_exclude_ip.ip4 && ip4.src == 172.18.0.0/16
I1226 07:11:29.318799      13 ovn-nbctl-legacy.go:1073] remove policy route from router ovn-cluster: match ip4.dst == $ovn.default.u2o_exclude_ip.ip4 && ip4.src == 172.18.0.0/16
I1226 07:11:29.329005      13 ovn-nbctl-legacy.go:1028] add policy route for router ovn-cluster: priority 31000, match ip4.dst == $ovn.default.u2o_exclude_ip.ip4 && ip4.src == 172.18.0.0/16, nextHop
I1226 07:11:29.363336      13 subnet.go:2131] add u2o interconnection policy for router: ovn-cluster, match ip4.src == 172.18.0.0/16, action reroute, nexthop 172.18.0.1
I1226 07:11:29.377388      13 subnet.go:2119] add u2o interconnection policy for router: ovn-cluster, match ip6.dst == fc00:f853:ccd:e793::/64 && ip6.dst != $ovn.default.u2o_exclude_ip.ip6, action allow
I1226 07:11:29.387790      13 ovn-nbctl-legacy.go:1017] remove inconsistent policy route from router ovn-cluster: match ip6.dst == fc00:f853:ccd:e793::/64 && ip6.dst != $ovn.default.u2o_exclude_ip.ip6
I1226 07:11:29.393538      13 ovn-nbctl-legacy.go:1073] remove policy route from router ovn-cluster: match ip6.dst == fc00:f853:ccd:e793::/64 && ip6.dst != $ovn.default.u2o_exclude_ip.ip6
I1226 07:11:29.404454      13 ovn-nbctl-legacy.go:1028] add policy route for router ovn-cluster: priority 31000, match ip6.dst == fc00:f853:ccd:e793::/64 && ip6.dst != $ovn.default.u2o_exclude_ip.ip6, nextHop
I1226 07:11:29.444811      13 subnet.go:2125] add u2o interconnection policy for router: ovn-cluster, match ip6.dst == $ovn.default.u2o_exclude_ip.ip6 && ip6.src == fc00:f853:ccd:e793::/64, action allow
I1226 07:11:29.459253      13 ovn-nbctl-legacy.go:1017] remove inconsistent policy route from router ovn-cluster: match ip6.dst == $ovn.default.u2o_exclude_ip.ip6 && ip6.src == fc00:f853:ccd:e793::/64
I1226 07:11:29.466960      13 ovn-nbctl-legacy.go:1073] remove policy route from router ovn-cluster: match ip6.dst == $ovn.default.u2o_exclude_ip.ip6 && ip6.src == fc00:f853:ccd:e793::/64
I1226 07:11:29.484486      13 ovn-nbctl-legacy.go:1028] add policy route for router ovn-cluster: priority 31000, match ip6.dst == $ovn.default.u2o_exclude_ip.ip6 && ip6.src == fc00:f853:ccd:e793::/64, nextHop
I1226 07:11:29.530990      13 subnet.go:2131] add u2o interconnection policy for router: ovn-cluster, match ip6.src == fc00:f853:ccd:e793::/64, action reroute, nexthop fc00:f853:ccd:e793::1
```

3. 新创建的 underlay pod 无法成功

```
Events:
  Type     Reason                  Age    From               Message
  ----     ------                  ----   ----               -------
  Normal   Scheduled               6m59s  default-scheduler  Successfully assigned kube-system/coredns-787d4945fb-49f7r to kube-ovn-control-plane
  Warning  FailedCreatePodSandBox  3m38s  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "3d673d9b88d8a1f5d95cd4cabdf716f99cfe436bacdd63f09bff0406878af41a": plugin type="kube-ovn" failed (add): RPC failed; request ip return 500 configure nic failed fc00:f853:ccd:e793::e network not ready after 200 ping fc00:f853:ccd:e793::4
  Warning  FailedCreatePodSandBox  17s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "94b8db793e5b635937bd12fe28dfe184d7bd188dbe1f98f3ddcabad76650170c": plugin type="kube-ovn" failed (add): RPC failed; request ip return 500 configure nic failed fc00:f853:ccd:e793::e network not ready after 200 ping fc00:f853:ccd:e793::4
```

**Comment by changluyi** [comment]
> ```yaml
> u2oInterconnectionIP
> ```

感谢，知道问题了。

**Comment by changluyi** [comment]
> 重启 kube-ovn-controller 后发现如下问题：
> 
> 1. Pod 会使用到 u2oInterconnectionIP
> 
> ```yaml
> apiVersion: kubeovn.io/v1
> kind: Subnet
> metadata:
>   creationTimestamp: "2022-12-26T07:07:03Z"
>   finalizers:
>   - kube-ovn-controller
>   generation: 2
>   name: ovn-default
>   resourceVersion: "2289"
>   uid: de28ba31-a48e-4302-a20e-b81892d8533b
> spec:
>   cidrBlock: 172.18.0.0/16,fc00:f853:ccd:e793::/64
>   default: true
>   excludeIps:
>   - 172.18.0.1
>   - 172.18.0.2
>   - 172.18.0.3
>   - fc00:f853:ccd:e793::1
>   - fc00:f853:ccd:e793::2
>   - fc00:f853:ccd:e793::3
>   gateway: 172.18.0.1,fc00:f853:ccd:e793::1
>   gatewayNode: ""
>   gatewayType: distributed
>   natOutgoing: true
>   private: false
>   protocol: Dual
>   provider: ovn
>   u2oInterconnection: true
>   vlan: ovn-vlan
>   vpc: ovn-cluster
> status:
>   activateGateway: ""
>   conditions:
>   - lastTransitionTime: "2022-12-26T07:07:06Z"
>     lastUpdateTime: "2022-12-26T07:11:29Z"
>     reason: ResetLogicalSwitchAclSuccess
>     status: "True"
>     type: Validated
>   - lastTransitionTime: "2022-12-26T07:07:06Z"
>     lastUpdateTime: "2022-12-26T07:07:06Z"
>     reason: ResetLogicalSwitchAclSuccess
>     status: "True"
>     type: Ready
>   - lastTransitionTime: "2022-12-26T07:07:06Z"
>     lastUpdateTime: "2022-12-26T07:07:06Z"
>     message: Not Observed
>     reason: Init
>     status: Unknown
>     type: Error
>   dhcpV4OptionsUUID: ""
>   dhcpV6OptionsUUID: ""
>   u2oInterconnectionIP: 172.18.0.4,fc00:f853:ccd:e793::4
>   v4availableIPs: 65526
>   v4usingIPs: 5
>   v6availableIPs: 1.8446744073709552e+19
>   v6usingIPs: 5
> ```
> 
> ```
> I1226 07:13:20.391305      13 ipam.go:51] allocate v4 172.18.0.4 v6 fc00:f853:ccd:e793::4 mac 00:00:00:0D:DE:93 for kube-system/kube-ovn-pinger-bqw2c from subnet ovn-default
> ```
> 
> 2. 日志中存在反复 add/remove 路由的日志
> 
> ```
> I1226 07:11:29.229293      13 subnet.go:2119] add u2o interconnection policy for router: ovn-cluster, match ip4.dst == 172.18.0.0/16 && ip4.dst != $ovn.default.u2o_exclude_ip.ip4, action allow
> I1226 07:11:29.240596      13 ovn-nbctl-legacy.go:1017] remove inconsistent policy route from router ovn-cluster: match ip4.dst == 172.18.0.0/16 && ip4.dst != $ovn.default.u2o_exclude_ip.ip4
> I1226 07:11:29.246036      13 ovn-nbctl-legacy.go:1073] remove policy route from router ovn-cluster: match ip4.dst == 172.18.0.0/16 && ip4.dst != $ovn.default.u2o_exclude_ip.ip4
> I1226 07:11:29.255270      13 ovn-nbctl-legacy.go:1028] add policy route for router ovn-cluster: priority 31000, match ip4.dst == 172.18.0.0/16 && ip4.dst != $ovn.default.u2o_exclude_ip.ip4, nextHop
> I1226 07:11:29.293086      13 subnet.go:2125] add u2o interconnection policy for router: ovn-cluster, match ip4.dst == $ovn.default.u2o_exclude_ip.ip4 && ip4.src == 172.18.0.0/16, action allow
> I1226 07:11:29.312550      13 ovn-nbctl-legacy.go:1017] remove inconsistent policy route from router ovn-cluster: match ip4.dst == $ovn.default.u2o_exclude_ip.ip4 && ip4.src == 172.18.0.0/16
> I1226 07:11:29.318799      13 ovn-nbctl-legacy.go:1073] remove policy route from router ovn-cluster: match ip4.dst == $ovn.default.u2o_exclude_ip.ip4 && ip4.src == 172.18.0.0/16
> I1226 07:11:29.329005      13 ovn-nbctl-legacy.go:1028] add policy route for router ovn-cluster: priority 31000, match ip4.dst == $ovn.default.u2o_exclude_ip.ip4 && ip4.src == 172.18.0.0/16, nextHop
> I1226 07:11:29.363336      13 subnet.go:2131] add u2o interconnection policy for router: ovn-cluster, match ip4.src == 172.18.0.0/16, action reroute, nexthop 172.18.0.1
> I1226 07:11:29.377388      13 subnet.go:2119] add u2o interconnection policy for router: ovn-cluster, match ip6.dst == fc00:f853:ccd:e793::/64 && ip6.dst != $ovn.default.u2o_exclude_ip.ip6, action allow
> I1226 07:11:29.387790      13 ovn-nbctl-legacy.go:1017] remove inconsistent policy route from router ovn-cluster: match ip6.dst == fc00:f853:ccd:e793::/64 && ip6.dst != $ovn.default.u2o_exclude_ip.ip6
> I1226 07:11:29.393538      13 ovn-nbctl-legacy.go:1073] remove policy route from router ovn-cluster: match ip6.dst == fc00:f853:ccd:e793::/64 && ip6.dst != $ovn.default.u2o_exclude_ip.ip6
> I1226 07:11:29.404454      13 ovn-nbctl-legacy.go:1028] add policy route for router ovn-cluster: priority 31000, match ip6.dst == fc00:f853:ccd:e793::/64 && ip6.dst != $ovn.default.u2o_exclude_ip.ip6, nextHop
> I1226 07:11:29.444811      13 subnet.go:2125] add u2o interconnection policy for router: ovn-cluster, match ip6.dst == $ovn.default.u2o_exclude_ip.ip6 && ip6.src == fc00:f853:ccd:e793::/64, action allow
> I1226 07:11:29.459253      13 ovn-nbctl-legacy.go:1017] remove inconsistent policy route from router ovn-cluster: match ip6.dst == $ovn.default.u2o_exclude_ip.ip6 && ip6.src == fc00:f853:ccd:e793::/64
> I1226 07:11:29.466960      13 ovn-nbctl-legacy.go:1073] remove policy route from router ovn-cluster: match ip6.dst == $ovn.default.u2o_exclude_ip.ip6 && ip6.src == fc00:f853:ccd:e793::/64
> I1226 07:11:29.484486      13 ovn-nbctl-legacy.go:1028] add policy route for router ovn-cluster: priority 31000, match ip6.dst == $ovn.default.u2o_exclude_ip.ip6 && ip6.src == fc00:f853:ccd:e793::/64, nextHop
> I1226 07:11:29.530990      13 subnet.go:2131] add u2o interconnection policy for router: ovn-cluster, match ip6.src == fc00:f853:ccd:e793::/64, action reroute, nexthop fc00:f853:ccd:e793::1
> ```
> 
> 3. 新创建的 underlay pod 无法成功，怀疑和 ip 冲突相关
> 
> ```
> Events:
>   Type     Reason                  Age    From               Message
>   ----     ------                  ----   ----               -------
>   Normal   Scheduled               6m59s  default-scheduler  Successfully assigned kube-system/coredns-787d4945fb-49f7r to kube-ovn-control-plane
>   Warning  FailedCreatePodSandBox  3m38s  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "3d673d9b88d8a1f5d95cd4cabdf716f99cfe436bacdd63f09bff0406878af41a": plugin type="kube-ovn" failed (add): RPC failed; request ip return 500 configure nic failed fc00:f853:ccd:e793::e network not ready after 200 ping fc00:f853:ccd:e793::4
>   Warning  FailedCreatePodSandBox  17s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "94b8db793e5b635937bd12fe28dfe184d7bd188dbe1f98f3ddcabad76650170c": plugin type="kube-ovn" failed (add): RPC failed; request ip return 500 configure nic failed fc00:f853:ccd:e793::e network not ready after 200 ping fc00:f853:ccd:e793::4
> ```

fixed

**Comment by oilbeater** [comment]
日志中重复添加删除策略路由的问题还存在

**Comment by changluyi** [comment]
> emove inconsistent policy route



> 日志中重复添加删除策略路由的问题还存在

是AddPolicyRoute这个api，会先检查原先路由有没有存在，没有存在也会打印删除log，然后再添加策略路由。

**Comment by changluyi** [comment]
> > emove inconsistent policy route
> 
> > 日志中重复添加删除策略路由的问题还存在
> 
> 是AddPolicyRoute这个api，会先检查原先路由有没有存在，没有存在也会打印删除log，然后再添加策略路由。

image

**Review by oilbeater — APPROVED** [review]

**Review by zhangzujian — APPROVED** [review]

**Pull request merged**
