### PR TITLE
lb-svc is compatible with dual stack subnets and supports attachment network for device plugin types

### PR DESCRIPTION
**Pull request by coldzerofear**
lb-svc is compatible with dual stack subnets
lb-svc supports attachment network for device plugin types

# Pull Request

- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Features
- Bug fixes
- Docs
- Tests

## Which issue(s) this PR fixes

Fixes #(issue-number)

### CODE REVIEW

**Comment by oilbeater** [comment]
@coldzerofear, could you introduce the scenarios in which it is necessary to add device plugin devices to the lb-svc pods? I'm considering whether the vpc-nat-gateway also needs a similar configuration.

**Comment by coldzerofear** [comment]
> @coldzerofear, could you introduce the scenarios in which it is necessary to add device plugin devices to the lb-svc pods? I'm considering whether the vpc-nat-gateway also needs a similar configuration.

Some network providers use device plugins to allocate devices or enhance scheduling, multus supports passing deviceID assigned by device plugins to CNI for binding container networks. Although it is uncertain how many CNIs can benefit from it, I think it should be compatible with these features

**Comment by coldzerofear** [comment]
> @coldzerofear, could you introduce the scenarios in which it is necessary to add device plugin devices to the lb-svc pods? I'm considering whether the vpc-nat-gateway also needs a similar configuration.

I have another suggestion, hoping that lb's pod can have more configurable items, such as resource request size, so that lb pod can run with guaranteed QoS

**Comment by oilbeater** [comment]
> I have another suggestion, hoping that lb's pod can have more configurable items, such as resource request size, so that lb pod can run with guaranteed QoS

That make sense. I think we may need a template way to deploy lb-svc pod and vpc-nat-gateway.

**Review by oilbeater — APPROVED** [review]

**Pull request merged**
