### PR TITLE
fix: wrong info when update subnet from dual to ipv4 or ipv6.

### PR DESCRIPTION
**Pull request by xujunjie-cover**
when update subnet from dual to ipv4 or ipv6, available and used ip not correct

3506c800b925ac4f6d81109028928f4

#### What type of this PR
Examples of user facing changes:
- Bug fixes

### CODE REVIEW

**Comment by oilbeater** [comment]
Looks good to me. But I am wondering what will happens to the ipam when change subnet protocol

**Comment by xujunjie-cover** [comment]
> Looks good to me. But I am wondering what will happens to the ipam when change subnet protocol

When change from v4 or v6 to dual，will add v6 or v4 cidr，excludeips to ipam.
When change from dual to single stack, will do nothing to ipam.

**Comment by oilbeater** [comment]
Got it. It should be changed later, thanks!

**Comment by oilbeater** [comment]
backport down to release-1.8

**Pull request merged**
