### PR TITLE
fix ovn build

### PR DESCRIPTION
**Pull request by zhangzujian**
- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

### What type of this PR
Examples of user facing changes:
- Features
- Bug fixes
- Docs
- Tests

### Which issue(s) this PR fixes:
Fixes #(issue-number)

### <samp>🤖 Generated by Copilot at 32be8b5</samp>

Update Windows build workflow to use a new ovn patch. This patch fixes some build errors on Windows by renaming some code to `ovs_build_helpers`.

### <samp>🤖 Generated by Copilot at 32be8b5</samp>

> _`ovn` patch applied_
> _Renaming build helpers_
> _Windows errors fixed_

### <samp>🤖 Generated by Copilot at 32be8b5</samp>

* Apply a new patch from ovn repository to fix build errors on Windows ([link](https://github.com/kubeovn/kube-ovn/pull/3166/files?diff=unified&w=0#diff-a3ae20db8d6f829cce559bf09c6fa26bf26822b30ab4994444b49a0b9909470eL115-R129))

### CODE REVIEW

**Comment by mingoooo** [comment]
@zhangzujian Hi, I still can not start up northd with this build in my macbook(m2), do you have a same problem?

**Comment by zhangzujian** [comment]
> @zhangzujian Hi, I still can not start up northd with this build in my macbook(m2), do you have a same problem?

What's the error?

**Comment by mingoooo** [comment]
> > @zhangzujian Hi, I still can not start up northd with this build in my macbook(m2), do you have a same problem?
> 
> What's the error?

did not get the error log in northd.log, but also did not find the pid file...

**Comment by mingoooo** [comment]
> > > @zhangzujian Hi, I still can not start up northd with this build in my macbook(m2), do you have a same problem?
> > 
> > 
> > What's the error?
> 
> did not get the error log in northd.log, but also did not find the pid file...

```
2023-09-08T02:13:03.231Z|00002|ovn_northd|INFO|OVN internal version is : [22.12.1-20.27.0-70.6]
2023-09-08T02:13:03.231Z|00002|vlog(monitor)|INFO|closing log file
2023-09-08T02:13:03.232Z|00003|reconnect|INFO|tcp:[172.18.0.3]:6641: connecting...
2023-09-08T02:13:03.232Z|00004|reconnect|INFO|tcp:[172.18.0.3]:6641: connected
2023-09-08T02:13:03.232Z|00005|ovn_northd|INFO|OVN NB IDL reconnected, force recompute.
2023-09-08T02:13:03.232Z|00006|reconnect|INFO|tcp:[172.18.0.3]:6642: connecting...
2023-09-08T02:13:03.232Z|00007|reconnect|INFO|tcp:[172.18.0.3]:6642: connected
2023-09-08T02:13:03.232Z|00008|ovn_northd|INFO|OVN SB IDL reconnected, force recompute.
2023-09-08T02:13:03.233Z|00009|ovn_northd|INFO|ovn-northd lock acquired. This ovn-northd instance is now active.
2023-09-08T02:13:13.238Z|00010|memory|INFO|8596 kB peak resident set size after 10.0 seconds
```

from ovn-northd.log

**Comment by mingoooo** [comment]
FYI, all fine in amd64, not sure the cause...

**Pull request merged**
