### PR TITLE
[bugfix] Unable to correctly gc port group

### PR DESCRIPTION
**Pull request by cmdy**
# Pull Request

- [ ] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Bug fixes

## Which issue(s) this PR fixes

1. When `EnableNP`  is not enabled, cannot gc node and subnet port group
2. #4456

### CODE REVIEW

**Comment by bobz965** [comment]
@cmdy Hi, please fix the DCO.  use `git commit -s `

**Comment by cmdy** [comment]
> @cmdy Hi, please fix the DCO. use `git commit -s `

Hi, I find that the check task failed. What should I do to merge the code? Please review my code.

**Review by bobz965 — APPROVED** [review]

**Comment by bobz965** [comment]
@cmdy Does master has the same issue? would you please help to fix it too?

**Comment by cmdy** [comment]
> @cmdy Does master has the same issue? would you please help to fix it too?

Okay, I'd be happy to. you can assign it to me.

**Review by oilbeater — APPROVED** [review]

**Comment by oilbeater** [comment]
Thanks! @cmdy

**Pull request merged**
