### PR TITLE
add trivy scan

### PR DESCRIPTION
**Pull request by fengshunli**
- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

#### What type of this PR
Examples of user facing changes:

- CI

#### Which issue(s) this PR fixes:
Fixes #(issue-number)

### CODE REVIEW

**Comment by oilbeater** [comment]
Need pass the action on forked repo before merge

**Comment by zhangzujian** [comment]
```txt
[Invalid workflow file: .github/workflows/build-x86-image.yaml#L1235](https://github.com/kubeovn/kube-ovn/actions/runs/4239971498/workflow)
The workflow is not valid. .github/workflows/build-x86-image.yaml (Line: 1235, Col: 9): Unexpected value 'image-ref' .github/workflows/build-x86-image.yaml (Line: 1236, Col: 9): Unexpected value 'exit-code'
```

**Comment by fengshunli** [comment]
https://github.com/fengshunli/kube-ovn/actions/runs/4240106928/jobs/7369489192 @zhangzujian The tar package kube-ovn.tar is in that path, why can’t I read it

**Comment by zhangzujian** [comment]
```
unable to open kube-ovn.tar as a Docker image: tarball must contain only a single image to be used with tarball.Image
```

`kube-ovn.tar` contains two images.

**Comment by fengshunli** [comment]
Can docker pull kubeovn/kube-ovn:$TAG this image and then scan it?

**Comment by fengshunli** [comment]
done

**Comment by oilbeater** [comment]
I cannot see much benefit from this PR. 

We have to maintain two security scan config one from the Makefile and one from workflows. It's easy to lead config and version miss match, just like now the trivy version in apt is 0.37.3 but the version in action is 0.37.2. And the args of trivy are also inconsistent.

The workflow in the PR uses matrix which will trigger extra jobs and make the workflow even more complex.

**Comment by fengshunli** [comment]
It is also possible without matrix, but matrix can be processed in parallel

**Comment by fengshunli** [comment]
The version corresponding to trivy-action@master is the latest version of trivy, which is more convenient to keep in sync with the community

**Pull request closed without merging**
