### PR TITLE
skip the missing of kube-dns

### LINKED ISSUE #1285: kubectl-ko is checking the old svc name kube-dns, which leads to exiting prematurely
# Expected Behavior
remove checking kube-dns svc
# Actual Behavior
```
https://github.com/kubeovn/kube-ovn/blob/master/dist/images/kubectl-ko#L270
kubectl get svc kube-dns -n kube-system
```

# Steps to Reproduce the Problem

1. kubectl ko diagnose all
```
[Step 6/6] Run network diagnose
NAME              CREATED AT
vpcs.kubeovn.io   2022-02-07T08:31:42Z
NAME                          CREATED AT
vpc-nat-gateways.kubeovn.io   2022-02-07T08:31:42Z
NAME                 CREATED AT
subnets.kubeovn.io   2022-02-07T08:31:42Z
NAME             CREATED AT
ips.kubeovn.io   2022-02-07T08:31:42Z
NAME               CREATED AT
vlans.kubeovn.io   2022-02-07T08:31:42Z
NAME                           CREATED AT
provider-networks.kubeovn.io   2022-02-07T08:31:42Z
Error from server (NotFound): services "kube-dns" not found
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
[root@k8s-ovn2 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
  ```

- kube-ovn version:
  
  ```
Kube-OVN:
  Version:       v1.9.0
  Build:         2022-01-12_05:50:51
  Commit:        git-ee7b17c
  Go Version:    go1.17.5
  Arch:          amd64
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```

### PR DESCRIPTION
**Pull request by gongysh2004**
#### What type of this PR
Examples of user facing changes:
- Bug fixes

#### Which issue(s) this PR fixes:
Fixes #1285

### CODE REVIEW

**Comment by gongysh2004** [comment]
have tested with this output:
`Error from server (NotFound): services "kube-dns" not found

Warning: kube-dns doesn't exist, maybe there is coredns service.`

the first line is the output of kubect get svc kube-dns; the second line is output by the change.

**Comment by oilbeater** [comment]
@gongysh2004 please also update the `install.sh` section

**Comment by gongysh2004** [comment]
> @gongysh2004 please also update the `install.sh` section

done

**Review by oilbeater — APPROVED** [review]

**Comment by oilbeater** [comment]
Thanks! @gongysh2004

**Pull request merged**
