### PR TITLE
fix: kube-ovn-controller cannot be ready when ENABLE_METRICS is false

### LINKED ISSUE #4862: [BUG] kube-ovn-controller cannot be ready when ENABLE_METRICS is false
### Kube-OVN Version

v1.14.0

### Kubernetes Version

v1.29.5

### Operation-system/Kernel Version

"Ubuntu 22.04.5 LTS" 6.8.0-50-generic

### Description

1、当关闭metrics high kube-ovn-controller的pod不能ready
2、kube-ovn-controller通过10660端口进行健康检查
image
3、但是当ENABLE_METRICS 设置成false时，conteoller不会开启10660端口的监听
image
4、但是在cni的逻辑中，即使ENABLE_METRICS 设置成false，也会开启10665的监听
image

### Steps To Reproduce

1、helm chart设置ENABLE_METRICS 为false
2、启动kubeovn，发现controller无法启动

### Current Behavior

controller健康检查失败

### Expected Behavior

controller健康检查在关闭metric的情况下能够通过

### PR DESCRIPTION
**Pull request by zcq98**
# Pull Request

- [x] Make sure you have followed [Kube-OVN Code Style](https://github.com/kubeovn/kube-ovn/blob/master/CODE_STYLE.md).

## What type of this PR

Examples of user facing changes:

- Bug fixes

## Which issue(s) this PR fixes

Fixes #4862

### CODE REVIEW

**Review by bobz965 — APPROVED** [review]

**Comment by zcq98** [comment]
@zhangzujian could you help review this?

**Comment by oilbeater** [comment]
This will also enable the metrics endpoint, which is not the intended purpose of this configuration.

**Comment by bobz965** [comment]
> This will also enable the metrics endpoint, which is not the intended purpose of this configuration.

那就要把这个配置项用上，而不是去除这个配置项。也还要解决关闭的情况下，健康检查的问题。
在yaml 模版中要处理？难道不开启 enable metric 就不进行健康检查么？ 这样好像也不合适

**Comment by oilbeater** [comment]
健康检查应该只检查端口是否开启就可以，不需要访问 metrics 内容

**Comment by bobz965** [comment]
> 健康检查应该只检查端口是否开启就可以，不需要访问 metrics 内容

我们这边的理解是 enalbe metric 为 true， 服务才会监听在 10660 ，否则现有逻辑直接 return ，没有监听

**Pull request closed without merging**
